/**
 * Generated by @openapi-codegen
 *
 * @version 1.0
 */
export enum WebSocketEventEvent {
  requestAllGames = 'requestAllGames',
  createGame = 'createGame',
  joinGame = 'joinGame',
  leaveGame = 'leaveGame',
  gameCreated = 'gameCreated',
  gameUpdated = 'gameUpdated',
  allGames = 'allGames',
  exception = 'exception',
}

export type UsernameLoginRequestDTO = {
  username: string
}

export type User = {
  /**
   * Unique user ID.
   *
   * @example 1
   */
  id: number
  username: string
}

export type UsernameLoginResponseDTO = {
  accessToken: string
  user: User
}

export type MeDTO = {
  /**
   * Unique user ID.
   *
   * @example 1
   */
  id?: number
  username?: string
}

export type CreateGameRequestDto = {
  hostId: number
}

export type GridSize = {
  width: number
  height: number
}

export type GamePlayer = {
  id: number
  user: User
}

export type Game = {
  id: number
  host: User
  gridSize: GridSize
  maxPlayers: number
  timeLimitSeconds: number
  cardVisibleTimeSeconds: number
  startedAt: Record<string, any>
  players: GamePlayer[]
  /**
   * @format date-time
   */
  createdAt: string
  /**
   * @format date-time
   */
  updatedAt: string
}

export type JoinGameRequestDto = {
  userId: number
  gameId: number
}

export type LeaveGameRequestDto = {
  userId: number
  gameId: number
}

export type ExceptionResponseDto = {
  message: string
}

export type WebSocketEvent = {
  event: WebSocketEventEvent
}
