/**
 * Generated by @openapi-codegen
 *
 * @version 1.0
 */
export type MeDTO = {
  /**
   * Unique user ID.
   *
   * @example 1
   */
  id?: number
  username?: string
}

export type UsernameLoginRequestDTO = {
  username: string
}

export type UserDTO = {
  /**
   * Unique user ID.
   *
   * @example 1
   */
  id: number
  username: string
}

export type UsernameLoginResponseDTO = {
  accessToken: string
  refreshToken: string
  user: UserDTO
}

export type RefreshTokenResponseDTO = {
  accessToken: string
}
