/**
 * Generated by @openapi-codegen
 *
 * @version 1.0
 */
export enum WebSocketEventEvent {
  requestAllGames = 'requestAllGames',
  createGame = 'createGame',
  joinGame = 'joinGame',
  leaveGame = 'leaveGame',
  gameCreated = 'gameCreated',
  gameUpdated = 'gameUpdated',
  allGames = 'allGames',
  requestStartGame = 'requestStartGame',
  exception = 'exception',
}

export type UsernameLoginRequestDTO = {
  username: string
}

export type User = {
  /**
   * Unique user ID.
   *
   * @example 1
   */
  id: number
  username: string
}

export type UsernameLoginResponseDTO = {
  accessToken: string
  user: User
}

export type MeDTO = {
  /**
   * Unique user ID.
   *
   * @example 1
   */
  id?: number
  username?: string
}

export type CreateGameRequestDto = {
  hostId: number
}

export type GridSize = {
  width: number
  height: number
}

export type GamePlayer = {
  user: User
  isOnTurn: boolean
  turnCount: number
  score: number
}

export type Game = {
  id: number
  host: User
  gridSize: GridSize
  maxPlayers: number
  timeLimitSeconds: number
  turnLimitSeconds: number
  cardVisibleTimeSeconds: number
  startedAt: string
  finishedAt: string
  players: GamePlayer[]
}

export type JoinGameRequestDto = {
  userId: number
  gameId: number
}

export type LeaveGameRequestDto = {
  userId: number
  gameId: number
}

export type ExceptionResponseDto = {
  message: string
}

export type StartGameRequestDto = {
  userId: number
  gameId: number
}

export type WebSocketEvent = {
  event: WebSocketEventEvent
}
